micronaut:
  application:
    name: RESTCRUD
datasources:
  default:
    url: jdbc:mysql://localhost:3306/rest-crud
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'root'
    schema-generate: CREATE
    dialect: mysql

